delimiter $
begin not atomic
    -- 13/05/2021 2
    if (select count(*) from applied_updates where id='130520212') = 0 then
        -- Fix damage and armor of starting mobs.
        UPDATE `creature_template` SET `dmg_min` = 1, `dmg_max` = 2, `armor` = 16 WHERE `entry` IN (6, 707, 1512, 2955, 3098);
        UPDATE `creature_template` SET `dmg_min` = 1, `dmg_max` = 2, `armor` = 15 WHERE `entry` = 1501;

        insert into applied_updates values ('130520212');
    end if;

    -- 27/05/2021 1
	if (select count(*) from applied_updates where id='270520211') = 0 then
        DROP TABLE IF EXISTS `npc_trainer`;
        CREATE TABLE IF NOT EXISTS `npc_trainer` (
            `template_entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
            `spell` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
            `spellcost` INT(10) UNSIGNED NOT NULL DEFAULT '0',
            `talentpointcost` INT(10) UNSIGNED NOT NULL DEFAULT '0',
            `skillpointcost` INT(10) UNSIGNED NOT NULL DEFAULT '0',
            `reqskill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
            `reqskillvalue` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
            `reqlevel` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
            UNIQUE INDEX `template_entry_spell` (`template_entry`, `spell`) USING BTREE
        )
        COLLATE='utf8mb4_general_ci'
        ENGINE=InnoDB
        ;

        DROP TABLE IF EXISTS `spell_chain`;
        CREATE TABLE IF NOT EXISTS `spell_chain` (
            `spell_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
            `prev_spell` MEDIUMINT(8) UNSIGNED NULL DEFAULT '0',
            `first_spell` MEDIUMINT(8) UNSIGNED NULL DEFAULT '0',
            `rank` TINYINT(3) UNSIGNED NULL DEFAULT '0',
            `req_spell` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL,
            PRIMARY KEY (`spell_id`) USING BTREE
        )
        COLLATE='utf8mb4_general_ci'
        ENGINE=InnoDB;

        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (5, 116, 50, 0, 0, 0, 0, 4);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (5, 118, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (5, 143, 100, 0, 0, 0, 0, 6);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (5, 205, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (5, 587, 100, 0, 0, 0, 0, 6);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (5, 1459, 10, 0, 0, 0, 0, 1);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (5, 2136, 100, 0, 0, 0, 0, 6);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (5, 5143, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (5, 5504, 50, 0, 0, 0, 0, 4);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (7, 17, 100, 0, 0, 0, 0, 6);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (7, 139, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (7, 589, 50, 0, 0, 0, 0, 4);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (7, 591, 100, 0, 0, 0, 0, 6);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (7, 1243, 10, 0, 0, 0, 0, 1);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (7, 2052, 50, 0, 0, 0, 0, 4);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (13, 172, 100, 0, 0, 0, 0, 4);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (13, 980, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (16, 324, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (16, 339, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (16, 467, 100, 0, 0, 0, 0, 6);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (16, 529, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (16, 774, 80, 0, 0, 0, 0, 4);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (16, 1126, 10, 0, 0, 0, 0, 1);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (16, 5176, 100, 0, 0, 0, 0, 6);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (22, 100, 50, 0, 0, 0, 0, 4);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (22, 1715, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (25, 53, 50, 0, 0, 0, 0, 4);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (25, 921, 50, 0, 0, 0, 0, 4);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (25, 1757, 100, 0, 0, 0, 0, 6);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (25, 1776, 100, 0, 0, 0, 0, 6);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (25, 1784, 10, 0, 0, 0, 0, 1);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (25, 5277, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (25, 6760, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (28, 639, 100, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (28, 649, 10, 0, 0, 0, 0, 4);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (28, 678, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (28, 679, 10, 0, 0, 0, 0, 1);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (28, 1022, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (28, 3127, 200, 0, 0, 0, 0, 8);
        INSERT INTO `npc_trainer` (`template_entry`, `spell`, `spellcost`, `talentpointcost`, `skillpointcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES (28, 5606, 200, 0, 0, 0, 0, 8);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (2098, 0, 2098, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1022, 0, 1022, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (5176, 0, 5176, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (980, 0, 980, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (921, 0, 921, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (774, 0, 774, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (710, 0, 710, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (5504, 0, 5504, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (679, 0, 679, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (5143, 0, 5143, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (3127, 0, 3127, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (2812, 0, 2812, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1784, 0, 1784, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1776, 0, 1776, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (2136, 0, 2136, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1752, 0, 1752, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1715, 0, 1715, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1459, 0, 1459, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1243, 0, 1243, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1126, 0, 1126, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1719, 0, 1719, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (649, 0, 649, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (17, 0, 17, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (324, 0, 324, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (589, 0, 589, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (172, 0, 172, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (7384, 0, 7384, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (139, 0, 139, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (118, 0, 118, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (116, 0, 116, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (100, 0, 100, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (53, 0, 53, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (339, 0, 339, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (403, 0, 403, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (421, 0, 421, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (467, 0, 467, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (587, 0, 587, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (635, 0, 635, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (5277, 0, 5277, 1, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (7887, 7384, 7384, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (6760, 2098, 2098, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (5606, 649, 649, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (6222, 172, 172, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (7372, 1715, 1715, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (6178, 100, 100, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (2052, 2050, 2050, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (639, 635, 635, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (591, 585, 585, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (678, 679, 679, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (782, 467, 467, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1014, 980, 980, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (205, 116, 116, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1757, 1752, 1752, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (529, 403, 403, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (143, 133, 133, 2, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (6223, 6222, 172, 3, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (7373, 7372, 1715, 3, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1866, 678, 679, 3, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (647, 639, 635, 3, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (5609, 5606, 649, 3, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1075, 782, 467, 3, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (6217, 1014, 980, 3, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (680, 1866, 679, 4, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1026, 647, 635, 4, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (7648, 6223, 172, 4, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (2495, 680, 679, 5, 0);
        INSERT INTO `spell_chain` (`spell_id`, `prev_spell`, `first_spell`, `rank`, `req_spell`) VALUES (1042, 1026, 635, 5, 0);

        UPDATE `creature_template` SET `trainer_id` = 5 WHERE `entry` = 198;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 328;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 331;
        UPDATE `creature_template` SET `trainer_id` = 7 WHERE `entry` = 375;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 376;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 377;
        UPDATE `creature_template` SET `trainer_id` = 13 WHERE `entry` = 459;
        UPDATE `creature_template` SET `trainer_id` = 13 WHERE `entry` = 460;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 461;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 543;
        UPDATE `creature_template` SET `trainer_id` = 7 WHERE `entry` = 837;
        UPDATE `creature_template` SET `trainer_id` = 19 WHERE `entry` = 895;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 906;
        UPDATE `creature_template` SET `trainer_id` = 22 WHERE `entry` = 911;
        UPDATE `creature_template` SET `trainer_id` = 22 WHERE `entry` = 912;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 913;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 914;
        UPDATE `creature_template` SET `trainer_id` = 25 WHERE `entry` = 915;
        UPDATE `creature_template` SET `trainer_id` = 25 WHERE `entry` = 916;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 917;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 918;
        UPDATE `creature_template` SET `trainer_id` = 28 WHERE `entry` = 925;
        UPDATE `creature_template` SET `trainer_id` = 28 WHERE `entry` = 926;
        UPDATE `creature_template` SET `trainer_id` = 29 WHERE `entry` = 927;
        UPDATE `creature_template` SET `trainer_id` = 29 WHERE `entry` = 928;
        UPDATE `creature_template` SET `trainer_id` = 5 WHERE `entry` = 944;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 985;
        UPDATE `creature_template` SET `trainer_id` = 10 WHERE `entry` = 986;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 987;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 988;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 1226;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 1228;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 1229;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 1231;
        UPDATE `creature_template` SET `trainer_id` = 29 WHERE `entry` = 1232;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 1234;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 1404;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 1411;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 1901;
        UPDATE `creature_template` SET `trainer_id` = 22 WHERE `entry` = 2119;
        UPDATE `creature_template` SET `trainer_id` = 25 WHERE `entry` = 2122;
        UPDATE `creature_template` SET `trainer_id` = 7 WHERE `entry` = 2123;
        UPDATE `creature_template` SET `trainer_id` = 5 WHERE `entry` = 2124;
        UPDATE `creature_template` SET `trainer_id` = 13 WHERE `entry` = 2126;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 2127;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 2128;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 2129;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 2130;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 2131;
        UPDATE `creature_template` SET `trainer_id` = 47 WHERE `entry` = 2485;
        UPDATE `creature_template` SET `trainer_id` = 49 WHERE `entry` = 2489;
        UPDATE `creature_template` SET `trainer_id` = 48 WHERE `entry` = 2492;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 2878;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 2879;
        UPDATE `creature_template` SET `trainer_id` = 10 WHERE `entry` = 3030;
        UPDATE `creature_template` SET `trainer_id` = 10 WHERE `entry` = 3031;
        UPDATE `creature_template` SET `trainer_id` = 10 WHERE `entry` = 3032;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 3033;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 3034;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 3036;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 3038;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 3039;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 3040;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 3041;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 3042;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 3043;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 3044;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 3045;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 3046;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 3047;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 3048;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 3049;
        UPDATE `creature_template` SET `trainer_id` = 22 WHERE `entry` = 3059;
        UPDATE `creature_template` SET `trainer_id` = 16 WHERE `entry` = 3060;
        UPDATE `creature_template` SET `trainer_id` = 19 WHERE `entry` = 3061;
        UPDATE `creature_template` SET `trainer_id` = 11 WHERE `entry` = 3062;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 3063;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 3064;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 3065;
        UPDATE `creature_template` SET `trainer_id` = 10 WHERE `entry` = 3066;
        UPDATE `creature_template` SET `trainer_id` = 22 WHERE `entry` = 3153;
        UPDATE `creature_template` SET `trainer_id` = 19 WHERE `entry` = 3154;
        UPDATE `creature_template` SET `trainer_id` = 25 WHERE `entry` = 3155;
        UPDATE `creature_template` SET `trainer_id` = 13 WHERE `entry` = 3156;
        UPDATE `creature_template` SET `trainer_id` = 11 WHERE `entry` = 3157;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 3169;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 3170;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 3171;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 3172;
        UPDATE `creature_template` SET `trainer_id` = 10 WHERE `entry` = 3173;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 3306;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 3324;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 3325;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 3326;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 3327;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 3328;
        UPDATE `creature_template` SET `trainer_id` = 10 WHERE `entry` = 3344;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 3352;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 3353;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 3354;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 3401;
        UPDATE `creature_template` SET `trainer_id` = 10 WHERE `entry` = 3403;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 3406;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 3407;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 3408;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 3545;
        UPDATE `creature_template` SET `trainer_id` = 22 WHERE `entry` = 3593;
        UPDATE `creature_template` SET `trainer_id` = 25 WHERE `entry` = 3594;
        UPDATE `creature_template` SET `trainer_id` = 7 WHERE `entry` = 3595;
        UPDATE `creature_template` SET `trainer_id` = 19 WHERE `entry` = 3596;
        UPDATE `creature_template` SET `trainer_id` = 16 WHERE `entry` = 3597;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 3598;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 3599;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 3600;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 3601;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 3602;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 3620;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 3622;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 3624;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 3688;
        UPDATE `creature_template` SET `trainer_id` = 1005 WHERE `entry` = 3690;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 3698;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 3706;
        UPDATE `creature_template` SET `trainer_id` = 7 WHERE `entry` = 3707;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 3963;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 4087;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 4089;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 4090;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 4091;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 4092;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 4138;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 4146;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 4163;
        UPDATE `creature_template` SET `trainer_id` = 50 WHERE `entry` = 4165;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 4205;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 4214;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 4215;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 4217;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 4218;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 4219;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 4320;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 4563;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 4564;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 4565;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 4566;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 4567;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 4568;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 4582;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 4583;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 4584;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 4593;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 4594;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 4595;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 4606;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 4607;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 4608;
        UPDATE `creature_template` SET `trainer_id` = 1007 WHERE `entry` = 4732;
        UPDATE `creature_template` SET `trainer_id` = 1003 WHERE `entry` = 4752;
        UPDATE `creature_template` SET `trainer_id` = 1002 WHERE `entry` = 4753;
        UPDATE `creature_template` SET `trainer_id` = 1006 WHERE `entry` = 4772;
        UPDATE `creature_template` SET `trainer_id` = 1008 WHERE `entry` = 4773;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 5113;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 5114;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 5115;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 5116;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 5117;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 5141;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 5142;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 5143;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 5144;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 5145;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 5146;
        UPDATE `creature_template` SET `trainer_id` = 29 WHERE `entry` = 5147;
        UPDATE `creature_template` SET `trainer_id` = 29 WHERE `entry` = 5148;
        UPDATE `creature_template` SET `trainer_id` = 29 WHERE `entry` = 5149;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 5165;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 5166;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 5167;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 5171;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 5172;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 5173;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 5479;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 5480;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 5484;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 5489;
        UPDATE `creature_template` SET `trainer_id` = 29 WHERE `entry` = 5491;
        UPDATE `creature_template` SET `trainer_id` = 29 WHERE `entry` = 5492;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 5495;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 5496;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 5497;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 5498;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 5501;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 5504;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 5505;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 5506;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 5515;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 5516;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 5517;
        UPDATE `creature_template` SET `trainer_id` = 14 WHERE `entry` = 5612;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 5880;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 5882;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 5883;
        UPDATE `creature_template` SET `trainer_id` = 5 WHERE `entry` = 5884;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 5885;
        UPDATE `creature_template` SET `trainer_id` = 52 WHERE `entry` = 5957;
        UPDATE `creature_template` SET `trainer_id` = 51 WHERE `entry` = 5958;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 5994;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 6014;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 6018;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 6707;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 7311;
        UPDATE `creature_template` SET `trainer_id` = 1 WHERE `entry` = 7312;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 7315;
        UPDATE `creature_template` SET `trainer_id` = 1009 WHERE `entry` = 7953;
        UPDATE `creature_template` SET `trainer_id` = 1004 WHERE `entry` = 7954;
        UPDATE `creature_template` SET `trainer_id` = 29 WHERE `entry` = 8140;
        UPDATE `creature_template` SET `trainer_id` = 23 WHERE `entry` = 8141;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 8142;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 8308;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 9465;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 10086;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 10088;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 10089;
        UPDATE `creature_template` SET `trainer_id` = 273 WHERE `entry` = 10090;
        UPDATE `creature_template` SET `trainer_id` = 20 WHERE `entry` = 10930;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 11397;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 11401;
        UPDATE `creature_template` SET `trainer_id` = 8 WHERE `entry` = 11406;
        UPDATE `creature_template` SET `trainer_id` = 17 WHERE `entry` = 12042;
        UPDATE `creature_template` SET `trainer_id` = 26 WHERE `entry` = 13283;
        UPDATE `creature_template` SET `trainer_id` = 10 WHERE `entry` = 13417;
        UPDATE `creature_template` SET `trainer_id` = 1001 WHERE `entry` = 4753;
        UPDATE `creature_template` SET `trainer_id` = 1001 WHERE `entry` = 4752;
        UPDATE `creature_template` SET `trainer_id` = 1001 WHERE `entry` = 7954;
        UPDATE `creature_template` SET `trainer_id` = 1001 WHERE `entry` = 3690;
        UPDATE `creature_template` SET `trainer_id` = 1001 WHERE `entry` = 4772;
        UPDATE `creature_template` SET `trainer_id` = 1001 WHERE `entry` = 4732;
        UPDATE `creature_template` SET `trainer_id` = 1001 WHERE `entry` = 4773;
        UPDATE `creature_template` SET `trainer_id` = 1001 WHERE `entry` = 7953;

		insert into applied_updates values ('270520211');
    end if;
	
end $
delimiter ;