CREATE TABLE IF NOT EXISTS `applied_updates` (`id` varchar(9) NOT NULL DEFAULT '000000000', PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

delimiter $
begin not atomic
    -- 09/02/2021 1
    if (select count(*) from applied_updates where id='090220211') = 0 then
        alter table SkillLineAbility add column custom_PrecededBySpell int(11) not null default 0;
        
        UPDATE SkillLineAbility t1
        INNER JOIN SkillLineAbility t2 ON t2.SupercededBySpell = t1.Spell
        SET t1.custom_PrecededBySpell = t2.Spell;

        insert into applied_updates values ('090220211');
    end if;
	
	-- 04/07/2021 1
	if (select count(*) from applied_updates where id='040720211') = 0 then
        ALTER TABLE `TaxiNodes`
        ADD COLUMN `custom_Team` INT(3) NOT NULL DEFAULT -1 AFTER `Name_Mask`;

        UPDATE `TaxiNodes` SET `custom_Team` = -1 WHERE (`ID` = 1);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 2);
        UPDATE `TaxiNodes` SET `custom_Team` = -1 WHERE (`ID` = 3);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 4);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 5);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 6);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 7);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 8);
        UPDATE `TaxiNodes` SET `custom_Team` = -1 WHERE (`ID` = 9);
        UPDATE `TaxiNodes` SET `custom_Team` = 67 WHERE (`ID` = 10);
        UPDATE `TaxiNodes` SET `custom_Team` = 67 WHERE (`ID` = 11);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 12);
        UPDATE `TaxiNodes` SET `custom_Team` = 67 WHERE (`ID` = 13);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 14);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 15);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 16);
        UPDATE `TaxiNodes` SET `custom_Team` = 67 WHERE (`ID` = 17);
        UPDATE `TaxiNodes` SET `custom_Team` = 67 WHERE (`ID` = 18);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 19);
        UPDATE `TaxiNodes` SET `custom_Team` = 67 WHERE (`ID` = 20);
        UPDATE `TaxiNodes` SET `custom_Team` = 67 WHERE (`ID` = 21);
        UPDATE `TaxiNodes` SET `custom_Team` = 67 WHERE (`ID` = 22);
        UPDATE `TaxiNodes` SET `custom_Team` = 67 WHERE (`ID` = 23);
        UPDATE `TaxiNodes` SET `custom_Team` = -1 WHERE (`ID` = 24);
        UPDATE `TaxiNodes` SET `custom_Team` = 67 WHERE (`ID` = 25);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 26);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 27);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 28);
        UPDATE `TaxiNodes` SET `custom_Team` = 67 WHERE (`ID` = 29);
        UPDATE `TaxiNodes` SET `custom_Team` = 67 WHERE (`ID` = 30);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 31);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 32);
        UPDATE `TaxiNodes` SET `custom_Team` = 469 WHERE (`ID` = 33);
        UPDATE `TaxiNodes` SET `custom_Team` = -1 WHERE (`ID` = 36);
        UPDATE `TaxiNodes` SET `custom_Team` = -1 WHERE (`ID` = 35);
        UPDATE `TaxiNodes` SET `custom_Team` = -1 WHERE (`ID` = 34);
		
        insert into applied_updates values ('040720211');
    end if;

    -- 20/04/2022 1
    if (select count(*) from applied_updates where id='200420221') = 0 then
        DROP TABLE IF EXISTS `CreatureFamily`; 
        CREATE TABLE `CreatureFamily` (
          `ID` INT NOT NULL DEFAULT '0',
          `MinScale` FLOAT NOT NULL DEFAULT '0',
          `MinScaleLevel` INT NOT NULL DEFAULT '0',
          `MaxScale` FLOAT NOT NULL DEFAULT '0',
          `MaxScaleLevel` INT NOT NULL DEFAULT '0',
          `SkillLine_1` INT NOT NULL DEFAULT '0',
          `SkillLine_2` INT NOT NULL DEFAULT '0',
          PRIMARY KEY (`ID`)
          ) ENGINE=MyISAM DEFAULT CHARSET=utf8;
        
        INSERT INTO `CreatureFamily` VALUES (1,0.5,1,1.2,70,208,270); 
        INSERT INTO `CreatureFamily` VALUES (2,0.5,1,1.2,70,209,270); 
        INSERT INTO `CreatureFamily` VALUES (3,0.4,1,0.8,70,203,270); 
        INSERT INTO `CreatureFamily` VALUES (4,0.5,1,1.2,70,210,270); 
        INSERT INTO `CreatureFamily` VALUES (5,0.5,1,1.2,70,211,270); 
        INSERT INTO `CreatureFamily` VALUES (6,0.3,1,0.6,70,212,270); 
        INSERT INTO `CreatureFamily` VALUES (7,0.5,1,1.1,70,213,270); 
        INSERT INTO `CreatureFamily` VALUES (8,0.5,1,1.4,70,214,270); 
        INSERT INTO `CreatureFamily` VALUES (9,0.5,1,1.2,70,215,270); 
        INSERT INTO `CreatureFamily` VALUES (10,0.5,1,1.5,70,216,270); 
        INSERT INTO `CreatureFamily` VALUES (11,0.4,1,0.8,70,217,270); 
        INSERT INTO `CreatureFamily` VALUES (12,0.3,1,0.7,70,218,270); 
        INSERT INTO `CreatureFamily` VALUES (15,0.5,1,0.8,70,189,0); 
        INSERT INTO `CreatureFamily` VALUES (16,0.5,1,1,70,204,0); 
        INSERT INTO `CreatureFamily` VALUES (17,0.5,1,1.5,70,205,0); 
        INSERT INTO `CreatureFamily` VALUES (19,0.5,1,1.5,70,207,0); 
        INSERT INTO `CreatureFamily` VALUES (20,0.5,1,1,70,236,270); 
        INSERT INTO `CreatureFamily` VALUES (21,0.5,1,1.5,70,251,270); 
        INSERT INTO `CreatureFamily` VALUES (23,0.2,1,0.4,70,188,270); 
        
        INSERT INTO applied_updates VALUES ('200420221');
    end if;
    
    -- 09/06/2022 1
    if (select count(*) from applied_updates where id='090620221') = 0 then
        DROP TABLE IF EXISTS SpellVisualKit;
        CREATE TABLE SpellVisualKit(
        `ID` INT NOT NULL DEFAULT '0',
        `KitType` INT NOT NULL DEFAULT '0',
        `Anim` INT NOT NULL DEFAULT '0',
        PRIMARY KEY (`ID`)
        ) ENGINE=MyISAM DEFAULT CHARSET=utf8;

        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (1,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (2,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (3,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (4,3,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (5,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (6,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (7,0,110);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (8,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (9,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (10,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (11,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (12,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (13,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (14,1,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (15,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (16,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (17,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (18,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (19,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (20,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (21,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (22,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (23,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (24,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (25,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (26,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (27,2,129);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (28,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (30,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (31,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (32,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (33,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (34,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (35,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (36,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (37,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (38,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (39,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (40,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (41,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (42,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (43,0,54);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (44,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (45,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (46,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (47,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (48,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (49,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (50,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (51,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (52,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (53,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (54,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (55,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (56,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (57,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (58,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (59,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (60,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (61,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (62,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (63,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (64,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (65,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (66,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (67,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (68,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (69,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (70,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (71,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (72,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (73,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (74,0,58);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (75,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (76,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (77,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (78,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (79,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (80,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (81,0,117);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (82,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (83,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (84,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (85,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (86,0,57);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (87,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (88,0,59);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (89,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (90,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (91,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (92,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (93,0,57);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (94,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (95,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (96,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (97,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (98,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (99,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (100,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (101,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (102,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (103,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (104,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (105,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (106,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (107,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (108,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (109,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (110,0,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (111,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (112,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (113,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (114,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (115,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (116,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (117,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (118,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (119,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (120,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (121,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (122,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (123,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (124,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (125,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (126,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (127,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (128,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (129,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (130,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (131,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (132,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (133,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (134,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (135,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (136,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (137,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (138,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (139,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (140,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (141,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (142,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (143,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (144,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (145,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (146,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (147,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (148,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (149,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (150,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (151,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (152,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (153,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (154,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (155,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (156,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (157,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (158,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (159,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (160,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (161,0,111);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (162,0,100);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (163,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (164,0,42);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (165,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (166,0,60);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (167,0,48);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (168,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (169,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (170,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (171,0,212);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (172,0,112);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (173,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (174,0,59);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (175,0,169);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (176,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (177,0,169);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (178,0,188);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (179,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (180,0,181);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (181,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (182,0,131);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (183,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (184,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (185,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (186,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (187,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (188,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (189,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (190,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (191,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (192,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (193,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (194,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (195,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (196,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (197,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (198,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (199,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (200,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (201,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (202,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (203,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (204,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (205,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (206,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (207,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (208,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (209,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (211,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (212,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (213,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (214,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (215,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (216,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (217,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (218,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (219,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (220,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (221,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (222,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (223,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (224,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (225,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (226,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (227,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (228,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (229,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (230,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (231,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (232,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (233,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (234,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (235,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (237,0,59);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (238,0,113);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (239,0,112);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (240,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (241,0,114);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (242,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (243,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (244,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (245,2,220);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (246,0,117);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (247,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (248,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (249,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (250,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (251,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (252,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (253,0,191);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (254,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (255,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (256,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (257,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (258,0,169);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (259,0,55);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (260,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (261,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (262,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (263,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (264,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (265,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (266,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (267,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (268,0,131);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (269,0,213);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (270,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (271,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (272,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (273,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (274,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (275,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (276,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (277,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (278,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (279,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (280,0,129);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (281,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (282,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (283,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (284,2,224);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (285,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (286,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (287,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (288,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (289,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (290,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (291,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (292,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (293,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (294,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (295,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (296,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (297,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (298,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (299,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (300,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (301,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (302,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (303,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (304,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (305,0,217);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (306,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (307,0,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (308,0,188);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (309,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (310,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (311,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (312,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (313,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (314,1,169);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (315,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (316,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (317,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (318,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (319,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (320,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (321,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (322,2,124);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (323,2,131);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (324,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (325,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (326,1,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (327,0,190);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (328,1,176);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (329,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (330,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (331,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (332,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (333,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (334,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (335,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (336,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (337,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (338,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (339,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (340,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (341,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (342,2,224);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (343,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (344,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (345,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (346,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (347,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (348,1,215);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (349,2,129);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (350,0,55);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (351,0,55);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (352,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (353,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (354,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (355,1,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (356,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (357,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (358,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (359,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (360,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (361,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (362,1,345);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (363,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (364,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (365,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (366,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (367,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (368,0,168);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (369,0,226);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (370,2,226);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (371,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (372,0,211);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (373,1,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (378,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (379,0,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (380,0,217);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (381,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (382,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (383,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (384,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (385,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (386,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (387,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (388,0,55);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (389,0,55);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (390,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (391,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (392,0,55);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (393,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (394,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (395,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (396,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (397,0,169);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (398,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (399,0,214);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (400,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (401,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (402,2,224);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (403,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (404,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (405,0,220);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (406,0,59);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (407,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (408,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (409,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (410,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (411,0,132);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (412,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (413,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (414,0,112);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (415,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (416,0,57);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (417,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (418,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (419,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (420,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (421,1,345);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (422,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (423,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (424,0,112);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (425,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (426,2,148);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (427,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (428,1,168);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (429,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (430,2,224);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (431,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (432,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (433,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (434,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (435,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (436,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (437,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (438,0,59);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (439,0,133);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (440,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (441,1,215);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (442,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (443,0,216);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (444,0,218);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (445,2,169);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (446,1,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (447,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (448,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (449,0,133);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (450,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (451,1,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (452,1,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (453,1,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (454,1,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (455,1,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (456,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (457,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (458,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (459,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (460,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (461,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (462,0,59);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (463,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (464,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (465,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (466,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (467,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (468,0,58);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (469,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (470,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (471,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (472,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (473,2,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (474,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (475,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (476,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (477,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (478,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (479,0,132);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (480,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (481,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (482,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (483,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (484,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (485,1,215);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (486,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (487,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (488,2,117);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (489,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (490,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (491,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (492,0,57);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (493,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (494,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (495,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (496,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (497,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (498,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (499,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (500,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (501,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (502,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (503,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (504,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (505,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (506,0,214);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (507,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (508,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (509,1,138);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (510,0,55);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (511,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (512,0,190);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (513,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (514,2,184);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (515,1,172);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (516,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (517,0,131);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (518,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (519,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (520,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (521,0,124);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (522,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (523,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (524,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (525,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (526,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (527,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (528,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (529,0,181);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (530,2,124);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (531,1,169);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (532,2,131);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (533,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (534,2,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (535,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (536,0,135);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (537,0,173);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (538,0,133);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (539,0,132);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (540,1,124);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (541,2,152);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (542,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (543,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (544,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (545,0,60);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (546,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (547,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (548,0,132);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (549,1,124);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (550,1,125);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (551,1,124);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (552,0,168);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (553,1,176);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (554,0,170);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (555,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (556,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (557,0,132);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (558,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (559,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (560,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (561,0,187);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (562,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (563,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (564,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (565,1,215);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (566,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (586,2,129);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (587,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (588,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (589,0,51);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (606,1,124);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (607,2,216);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (608,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (609,3,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (626,0,201);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (646,0,57);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (647,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (648,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (649,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (650,0,190);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (651,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (652,0,190);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (653,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (654,0,190);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (655,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (656,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (657,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (658,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (659,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (660,2,132);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (661,2,129);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (662,0,132);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (663,1,215);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (664,2,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (665,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (666,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (667,0,131);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (668,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (686,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (687,1,215);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (688,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (689,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (690,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (691,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (692,3,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (693,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (694,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (695,3,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (696,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (697,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (698,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (699,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (700,3,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (701,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (702,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (703,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (704,0,59);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (705,0,125);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (716,2,225);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (717,2,225);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (718,2,225);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (719,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (720,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (721,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (722,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (723,0,185);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (724,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (725,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (726,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (727,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (728,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (729,2,224);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (730,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (731,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (732,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (733,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (734,0,55);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (735,0,113);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (736,3,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (737,1,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (738,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (739,2,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (740,2,129);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (741,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (742,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (743,0,230);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (744,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (745,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (746,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (747,0,57);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (748,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (749,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (750,0,227);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (751,0,227);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (752,0,227);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (753,0,227);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (764,0,132);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (765,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (766,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (767,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (768,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (769,2,215);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (770,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (771,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (772,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (773,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (774,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (775,0,176);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (776,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (777,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (778,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (779,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (780,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (781,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (782,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (783,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (784,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (785,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (786,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (787,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (788,0,112);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (789,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (790,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (791,2,231);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (792,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (793,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (794,0,129);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (795,1,129);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (796,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (797,0,227);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (798,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (799,0,50);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (800,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (801,0,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (802,0,230);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (803,0,111);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (804,0,48);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (805,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (806,1,215);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (807,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (808,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (809,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (810,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (811,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (812,0,55);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (813,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (814,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (815,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (816,2,129);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (817,0,31);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (818,2,223);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (819,0,231);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (820,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (821,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (822,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (823,0,56);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (824,2,55);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (825,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (826,0,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (827,0,52);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (828,1,125);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (829,0,346);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (830,2,347);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (831,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (832,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (833,0,132);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (834,2,129);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (835,1,188);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (836,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (837,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (838,0,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (839,1,170);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (840,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (841,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (842,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (843,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (844,0,55);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (845,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (846,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (847,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (848,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (849,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (850,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (851,1,220);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (852,2,220);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (853,0,180);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (854,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (855,0,132);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (856,1,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (857,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (858,2,0);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (859,0,53);
        INSERT INTO SpellVisualKit(ID,KitType,Anim) VALUES (860,1,0);

        INSERT INTO applied_updates VALUES ('090620221');
    end if;
end $
delimiter ;
