-- MySQL Script generated by MySQL Workbench
-- mié 15 abr 2020 02:51:04 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema alpha_realm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounts` ;

CREATE TABLE IF NOT EXISTS `accounts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `ip` VARCHAR(256) NOT NULL,
  `gmlevel` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `applied_updates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `applied_updates` ;

CREATE TABLE IF NOT EXISTS `applied_updates` (
  `id` VARCHAR(9) NOT NULL DEFAULT '000000000',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `characters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `characters` ;

CREATE TABLE IF NOT EXISTS `characters` (
  `guid` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Account Identifier',
  `name` VARCHAR(12) NOT NULL DEFAULT '',
  `race` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `gender` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `xp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `money` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `skin` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `face` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `hairstyle` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `haircolour` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `facialhair` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `bankslots` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `talentpoints` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `skillpoints` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `position_x` FLOAT NOT NULL DEFAULT '0',
  `position_y` FLOAT NOT NULL DEFAULT '0',
  `position_z` FLOAT NOT NULL DEFAULT '0',
  `map` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Map Identifier',
  `orientation` FLOAT NOT NULL DEFAULT '0',
  `taximask` LONGTEXT NULL DEFAULT NULL,
  `online` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `totaltime` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `leveltime` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `extra_flags` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `zone` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `taxi_path` TEXT NULL DEFAULT NULL,
  `drunk` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `health` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `power1` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `power2` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `power3` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `power4` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `power5` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`),
  INDEX `idx_account` (`account` ASC),
  INDEX `idx_online` (`online` ASC),
  INDEX `idx_name` (`name` ASC),
  CONSTRAINT `char_acc`
    FOREIGN KEY (`account`)
    REFERENCES `accounts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `character_deathbind`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_deathbind` ;

CREATE TABLE IF NOT EXISTS `character_deathbind` (
  `deathbind_id` INT(11) NOT NULL AUTO_INCREMENT,
  `player_guid` INT(11) UNSIGNED NOT NULL,
  `creature_binder_guid` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `deathbind_map` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `deathbind_zone` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `deathbind_position_x` FLOAT NOT NULL DEFAULT '0',
  `deathbind_position_y` FLOAT NOT NULL DEFAULT '0',
  `deathbind_position_z` FLOAT NOT NULL DEFAULT '0',
  PRIMARY KEY (`deathbind_id`),
  INDEX `fk_character_deathbind_characters1_idx` (`player_guid` ASC),
  CONSTRAINT `fk_character_deathbind_characters1`
    FOREIGN KEY (`player_guid`)
    REFERENCES `characters` (`guid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `character_inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_inventory` ;

CREATE TABLE IF NOT EXISTS `character_inventory` (
  `guid` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Global Unique Identifier',
  `creator` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `bag` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `slot` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `item_template` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Item Identifier',
  `stackcount` INT(11) UNSIGNED NOT NULL DEFAULT '1',
  `SpellCharges1` INT(11) NOT NULL DEFAULT '-1',
  `SpellCharges2` INT(11) NOT NULL DEFAULT '-1',
  `SpellCharges3` INT(11) NOT NULL DEFAULT '-1',
  `SpellCharges4` INT(11) NOT NULL DEFAULT '-1',
  `SpellCharges5` INT(11) NOT NULL DEFAULT '-1',
  PRIMARY KEY (`guid`),
  INDEX `idx_guid` (`owner` ASC),
  CONSTRAINT `owner_guid`
    FOREIGN KEY (`owner`)
    REFERENCES `characters` (`guid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `character_social`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_social` ;

CREATE TABLE IF NOT EXISTS `character_social` (
  `guid` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Character Global Unique Identifier',
  `friend` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Friend Global Unique Identifier',
  `ignore` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Friend Flags',
  PRIMARY KEY (`guid`, `friend`),
  INDEX `guid` (`guid` ASC),
  INDEX `friend` (`friend` ASC),
  CONSTRAINT `social_frn`
    FOREIGN KEY (`friend`)
    REFERENCES `characters` (`guid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `social_own`
    FOREIGN KEY (`guid`)
    REFERENCES `characters` (`guid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tickets` ;

CREATE TABLE IF NOT EXISTS `tickets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `is_bug` INT(1) NOT NULL DEFAULT '0',
  `account_name` VARCHAR(250) NOT NULL DEFAULT '',
  `account_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `character_name` VARCHAR(12) NOT NULL DEFAULT '',
  `text_body` TEXT NOT NULL,
  `submit_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `account_id` (`account_id` ASC),
  CONSTRAINT `tickets_ibfk_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `accounts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
