from enum import Enum


class CharList(Enum):
    CHAR_LIST_RETRIEVING = 0x24
    CHAR_LIST_RETRIEVED = 0x25
    CHAR_LIST_FAILED = 0x26
    LAST_CHAR_LIST_RESULT = 0x27


class CharCreate(Enum):
    CHAR_CREATE_IN_PROGRESS = 0x27
    CHAR_CREATE_SUCCESS = 0x28
    CHAR_CREATE_ERROR = 0x28
    CHAR_CREATE_FAILED = 0x2A
    CHAR_CREATE_NAME_IN_USE = 0x2B
    CHAR_CREATE_DISABLED = 0x2C
    LAST_CHAR_CREATE_RESULT = 0x2D


class CharDelete(Enum):
    CHAR_DELETE_IN_PROGRESS = 0x2D
    CHAR_DELETE_SUCCESS = 0x2E
    CHAR_DELETE_FAILED = 0x2F
    LAST_CHAR_DELETE_RESULT = 0x30


class CharLogin(Enum):
    CHAR_LOGIN_IN_PROGRESS = 0x30
    CHAR_LOGIN_SUCCESS = 0x31
    CHAR_LOGIN_NO_WORLD = 0x32
    CHAR_LOGIN_DUPLICATE_CHARACTER = 0x33
    CHAR_LOGIN_NO_INSTANCES = 0x34
    CHAR_LOGIN_FAILED = 0x35
    CHAR_LOGIN_DISABLED = 0x36
    LAST_CHAR_LOGIN_RESULT = 0x37