class EnvironmentalVariables:
    FORWARD_ADDRESS_OVERRIDE = 'FORWARD_ADDRESS_OVERRIDE'
    CONSOLE_MODE = 'CONSOLE_MODE'
    FORWARD_HOSTNAME_OVERRIDE = 'FORWARD_HOSTNAME_OVERRIDE'

    ACTIVE_ENV_VARS = [
        FORWARD_ADDRESS_OVERRIDE,
        CONSOLE_MODE,
        FORWARD_HOSTNAME_OVERRIDE
    ]
