class EnvironmentalVariables:
    FORWARD_ADDRESS_OVERRIDE = 'FORWARD_ADDRESS_OVERRIDE'
    CONSOLE_MODE = 'CONSOLE_MODE'

    ACTIVE_ENV_VARS = [
        FORWARD_ADDRESS_OVERRIDE,
        CONSOLE_MODE,
    ]
