from enum import IntEnum


class ItemClasses(IntEnum):
    ITEM_CLASS_CONSUMABLE = 0
    ITEM_CLASS_CONTAINER = 1
    ITEM_CLASS_WEAPON = 2
    ITEM_CLASS_JEWELRY = 3
    ITEM_CLASS_ARMOR = 4
    ITEM_CLASS_REAGENT = 5
    ITEM_CLASS_PROJECTILE = 6
    ITEM_CLASS_TRADE_GOODS = 7
    ITEM_CLASS_GENERIC = 8
    ITEM_CLASS_BOOK = 9
    ITEM_CLASS_MONEY = 10
    ITEM_CLASS_QUIVER = 11
    ITEM_CLASS_QUEST = 12
    ITEM_CLASS_KEY = 13
    ITEM_CLASS_PERMANENT = 14
    ITEM_CLASS_JUNK = 15


class ItemSubClasses(IntEnum):
    # Consumable
    ITEM_SUBCLASS_CONSUMABLE = 0
    ITEM_SUBCLASS_FOOD = 1
    ITEM_SUBCLASS_LIQUID = 2
    ITEM_SUBCLASS_POTION = 3
    ITEM_SUBCLASS_SCROLL = 4
    ITEM_SUBCLASS_BANDAGE = 5
    ITEM_SUBCLASS_HEALTHSTONE = 6
    ITEM_SUBCLASS_COMBAT_EFFECT = 7

    # Container
    ITEM_SUBCLASS_BAG = 0
    ITEM_SUBCLASS_SOUL_BAG = 1
    ITEM_SUBCLASS_HERB_BAG = 2
    ITEM_SUBCLASS_ENCHANTING_BAG = 3

    # Weapon
    ITEM_SUBCLASS_AXE = 0
    ITEM_SUBCLASS_TWOHAND_AXE = 1
    ITEM_SUBCLASS_BOW = 2
    ITEM_SUBCLASS_GUN = 3
    ITEM_SUBCLASS_MACE = 4
    ITEM_SUBCLASS_TWOHAND_MACE = 5
    ITEM_SUBCLASS_POLEARM = 6
    ITEM_SUBCLASS_SWORD = 7
    ITEM_SUBCLASS_TWOHAND_SWORD = 8
    ITEM_SUBCLASS_WEAPON_obsolete = 9
    ITEM_SUBCLASS_STAFF = 10
    ITEM_SUBCLASS_WEAPON_EXOTIC = 11
    ITEM_SUBCLASS_WEAPON_EXOTIC2 = 12
    ITEM_SUBCLASS_FIST_WEAPON = 13
    ITEM_SUBCLASS_MISC_WEAPON = 14
    ITEM_SUBCLASS_DAGGER = 15
    ITEM_SUBCLASS_THROWN = 16
    ITEM_SUBCLASS_SPEAR = 17
    ITEM_SUBCLASS_CROSSBOW = 18
    ITEM_SUBCLASS_WAND = 19
    ITEM_SUBCLASS_FISHING_POLE = 20

    # Armor
    ITEM_SUBCLASS_MISC = 0
    ITEM_SUBCLASS_CLOTH = 1
    ITEM_SUBCLASS_LEATHER = 2
    ITEM_SUBCLASS_MAIL = 3
    ITEM_SUBCLASS_PLATE = 4
    ITEM_SUBCLASS_BUCKLER = 5
    ITEM_SUBCLASS_SHIELD = 6
    ITEM_SUBCLASS_LIBRAM = 7
    ITEM_SUBCLASS_IDOL = 8
    ITEM_SUBCLASS_TOTEM = 9

    # Projectile
    ITEM_SUBCLASS_WAND_obslete = 0
    ITEM_SUBCLASS_BOLT_obslete = 1
    ITEM_SUBCLASS_ARROW = 2
    ITEM_SUBCLASS_BULLET = 3
    ITEM_SUBCLASS_THROWN_obslete = 4

    # Trade goods
    ITEM_SUBCLASS_TRADE_GOODS = 0
    ITEM_SUBCLASS_PARTS = 1
    ITEM_SUBCLASS_EXPLOSIVES = 2
    ITEM_SUBCLASS_DEVICES = 3
    ITEM_SUBCLASS_GEMS = 4
    ITEM_SUBCLASS_CLOTHS = 5
    ITEM_SUBCLASS_LEATHERS = 6
    ITEM_SUBCLASS_METAL_AND_STONE = 7
    ITEM_SUBCLASS_MEAT = 8
    ITEM_SUBCLASS_HERB = 9
    ITEM_SUBCLASS_ELEMENTAL = 10
    ITEM_SUBCLASS_OTHERS = 11
    ITEM_SUBCLASS_ENCHANTANTS = 12
    ITEM_SUBCLASS_MATERIALS = 13

    # Recipe
    ITEM_SUBCLASS_BOOK = 0
    ITEM_SUBCLASS_LEATHERWORKING = 1
    ITEM_SUBCLASS_TAILORING = 2
    ITEM_SUBCLASS_ENGINEERING = 3
    ITEM_SUBCLASS_BLACKSMITHING = 4
    ITEM_SUBCLASS_COOKING = 5
    ITEM_SUBCLASS_ALCHEMY = 6
    ITEM_SUBCLASS_FIRST_AID = 7
    ITEM_SUBCLASS_ENCHANTING = 8
    ITEM_SUBCLASS_FISHING = 9
    ITEM_SUBCLASS_JEWELCRAFTING = 10

    # Quiver
    ITEM_SUBCLASS_QUIVER0_obslete = 0
    ITEM_SUBCLASS_QUIVER1_obslete = 1
    ITEM_SUBCLASS_QUIVER = 2
    ITEM_SUBCLASS_AMMO_POUCH = 3

    # Keys
    ITEM_SUBCLASS_KEY = 0
    ITEM_SUBCLASS_LOCKPICK = 1

    # Misc
    ITEM_SUBCLASS_JUNK = 0
    ITEM_SUBCLASS_REAGENT = 1
    ITEM_SUBCLASS_PET = 2
    ITEM_SUBCLASS_HOLIDAY = 3
    ITEM_SUBCLASS_OTHER = 4
    ITEM_SUBCLASS_MOUNT = 5


class InventoryTypes(IntEnum):
    NONE_EQUIP = 0x00
    HEAD = 0x01
    NECK = 0x02
    SHOULDER = 0x03
    BODY = 0x04
    CHEST = 0x05
    WAIST = 0x06
    LEGS = 0x07
    FEET = 0x08
    WRIST = 0x09
    HAND = 0x0A
    FINGER = 0x0B
    TRINKET = 0x0C
    WEAPON = 0x0D
    SHIELD = 0x0E
    RANGED = 0x0F
    CLOAK = 0x10
    TWOHANDEDWEAPON = 0x11
    BAG = 0x12
    TABARD = 0x13
    ROBE = 0x14
    WEAPONMAINHAND = 0x15
    WEAPONOFFHAND = 0x16
    HOLDABLE = 0x17
    AMMO = 0x18
    THROWN = 0x19
    RANGEDRIGHT = 0x1A
    NUM_TYPES = 0x1B


class InventorySlots(IntEnum):
    SLOT_HEAD = 0
    SLOT_NECK = 1
    SLOT_SHOULDERS = 2
    SLOT_SHIRT = 3
    SLOT_CHEST = 4
    SLOT_WAIST = 5
    SLOT_LEGS = 6
    SLOT_FEET = 7
    SLOT_WRISTS = 8
    SLOT_HANDS = 9
    SLOT_FINGERL = 10
    SLOT_FINGERR = 11
    SLOT_TRINKETL = 12
    SLOT_TRINKETR = 13
    SLOT_BACK = 14
    SLOT_MAINHAND = 15
    SLOT_OFFHAND = 16
    SLOT_RANGED = 17
    SLOT_TABARD = 18

    # Misc Types
    SLOT_BAG1 = 19
    SLOT_BAG2 = 20
    SLOT_BAG3 = 21
    SLOT_BAG4 = 22
    SLOT_INBACKPACK = 23

    SLOT_ITEM_START = 23
    SLOT_ITEM_END = 39

    SLOT_BANK_ITEM_START = 39
    SLOT_BANK_ITEM_END = 63
    SLOT_BANK_BAG_1 = 63
    SLOT_BANK_BAG_2 = 64
    SLOT_BANK_BAG_3 = 65
    SLOT_BANK_BAG_4 = 66
    SLOT_BANK_BAG_5 = 67
    SLOT_BANK_BAG_6 = 68
    SLOT_BANK_END = 69


class InventoryStats(IntEnum):
    HEALTH = 0
    POWER = 1  # Mana energy etc
    AGILITY = 3
    STRENGTH = 4
    INTELLECT = 5
    SPIRIT = 6
    STAMINA = 7


class InventoryError(IntEnum):
    EQUIP_ERR_OK = 0
    EQUIP_ERR_CANT_EQUIP_LEVEL_I = 1  # ERR_CANT_EQUIP_LEVEL_I
    EQUIP_ERR_CANT_EQUIP_SKILL = 2  # ERR_CANT_EQUIP_SKILL
    EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT = 3  # ERR_WRONG_SLOT
    EQUIP_ERR_BAG_FULL = 4  # ERR_BAG_FULL
    EQUIP_ERR_NONEMPTY_BAG_OVER_OTHER_BAG = 5  # ERR_BAG_IN_BAG
    EQUIP_ERR_ONLY_AMMO_CAN_GO_HERE = 6  # ERR_AMMO_ONLY
    EQUIP_ERR_NO_REQUIRED_PROFICIENCY = 7  # ERR_PROFICIENCY_NEEDED
    EQUIP_ERR_NO_EQUIPMENT_SLOT_AVAILABLE = 8  # ERR_NO_SLOT_AVAILABLE
    EQUIP_ERR_YOU_CAN_NEVER_USE_THAT_ITEM = 9  # ERR_CANT_EQUIP_EVER
    EQUIP_ERR_YOU_CAN_NEVER_USE_THAT_ITEM2 = 10  # ERR_CANT_EQUIP_EVER
    EQUIP_ERR_NO_EQUIPMENT_SLOT_AVAILABLE2 = 11  # ERR_NO_SLOT_AVAILABLE
    EQUIP_ERR_CANT_EQUIP_WITH_TWOHANDED = 12  # ERR_2HANDED_EQUIPPED
    EQUIP_ERR_CANT_DUAL_WIELD = 13  # ERR_2HSKILLNOTFOUND
    EQUIP_ERR_ITEM_DOESNT_GO_INTO_BAG = 14  # ERR_WRONG_BAG_TYPE
    EQUIP_ERR_ITEM_DOESNT_GO_INTO_BAG2 = 15  # ERR_WRONG_BAG_TYPE
    EQUIP_ERR_CANT_CARRY_MORE_OF_THIS = 16  # ERR_ITEM_MAX_COUNT
    EQUIP_ERR_NO_EQUIPMENT_SLOT_AVAILABLE3 = 17  # ERR_NO_SLOT_AVAILABLE
    EQUIP_ERR_ITEM_CANT_STACK = 18  # ERR_CANT_STACK
    EQUIP_ERR_ITEM_CANT_BE_EQUIPPED = 19  # ERR_NOT_EQUIPPABLE
    EQUIP_ERR_ITEMS_CANT_BE_SWAPPED = 20  # ERR_CANT_SWAP
    EQUIP_ERR_SLOT_IS_EMPTY = 21  # ERR_SLOT_EMPTY
    EQUIP_ERR_ITEM_NOT_FOUND = 22  # ERR_ITEM_NOT_FOUND
    EQUIP_ERR_CANT_DROP_SOULBOUND = 23  # ERR_DROP_BOUND_ITEM
    EQUIP_ERR_OUT_OF_RANGE = 24  # ERR_OUT_OF_RANGE
    EQUIP_ERR_TRIED_TO_SPLIT_MORE_THAN_COUNT = 25  # ERR_TOO_FEW_TO_SPLIT
    EQUIP_ERR_COULDNT_SPLIT_ITEMS = 26  # ERR_SPLIT_FAILED
    EQUIP_ERR_MISSING_REAGENT = 27  # ERR_SPELL_FAILED_REAGENTS_GENERIC
    EQUIP_ERR_NOT_ENOUGH_MONEY = 28  # ERR_NOT_ENOUGH_MONEY
    EQUIP_ERR_NOT_A_BAG = 29  # ERR_NOT_A_BAG
    EQUIP_ERR_CAN_ONLY_DO_WITH_EMPTY_BAGS = 30  # ERR_DESTROY_NONEMPTY_BAG
    EQUIP_ERR_DONT_OWN_THAT_ITEM = 31  # ERR_NOT_OWNER
    EQUIP_ERR_CAN_EQUIP_ONLY1_QUIVER = 32  # ERR_ONLY_ONE_QUIVER
    EQUIP_ERR_MUST_PURCHASE_THAT_BAG_SLOT = 33  # ERR_NO_BANK_SLOT
    EQUIP_ERR_TOO_FAR_AWAY_FROM_BANK = 34  # ERR_NO_BANK_HERE
    EQUIP_ERR_ITEM_LOCKED = 35  # ERR_ITEM_LOCKED
    EQUIP_ERR_YOU_ARE_STUNNED = 36  # ERR_GENERIC_STUNNED
    EQUIP_ERR_YOU_ARE_DEAD = 37  # ERR_PLAYER_DEAD
    EQUIP_ERR_CANT_DO_RIGHT_NOW = 38  # ERR_CLIENT_LOCKED_OUT
    EQUIP_ERR_INT_BAG_ERROR = 39  # ERR_INTERNAL_BAG_ERROR
    EQUIP_ERR_CAN_EQUIP_ONLY1_BOLT = 40  # ERR_ONLY_ONE_BOLT
    EQUIP_ERR_CAN_EQUIP_ONLY1_AMMOPOUCH = 41  # ERR_ONLY_ONE_AMMO
    EQUIP_ERR_STACKABLE_CANT_BE_WRAPPED = 42  # ERR_CANT_WRAP_STACKABLE
    EQUIP_ERR_EQUIPPED_CANT_BE_WRAPPED = 43  # ERR_CANT_WRAP_EQUIPPED
    EQUIP_ERR_WRAPPED_CANT_BE_WRAPPED = 44  # ERR_CANT_WRAP_WRAPPED
    EQUIP_ERR_BOUND_CANT_BE_WRAPPED = 45  # ERR_CANT_WRAP_BOUND
    EQUIP_ERR_UNIQUE_CANT_BE_WRAPPED = 46  # ERR_CANT_WRAP_UNIQUE
    EQUIP_ERR_BAGS_CANT_BE_WRAPPED = 47  # ERR_CANT_WRAP_BAGS
    EQUIP_ERR_ALREADY_LOOTED = 48  # ERR_LOOT_GONE
    EQUIP_ERR_INVENTORY_FULL = 49  # ERR_INV_FULL
    EQUIP_ERR_BANK_FULL = 50  # ERR_BAG_FULL
    EQUIP_ERR_ITEM_IS_CURRENTLY_SOLD_OUT = 51  # ERR_VENDOR_SOLD_OUT
    EQUIP_ERR_BAG_FULL3 = 52  # ERR_BAG_FULL
    EQUIP_ERR_ITEM_NOT_FOUND2 = 53  # ERR_ITEM_NOT_FOUND
    EQUIP_ERR_ITEM_CANT_STACK2 = 54  # ERR_CANT_STACK
    EQUIP_ERR_BAG_FULL4 = 55  # ERR_BAG_FULL
    EQUIP_ERR_ITEM_SOLD_OUT = 56  # ERR_VENDOR_SOLD_OUT
    EQUIP_ERR_OBJECT_IS_BUSY = 57  # ERR_OBJECT_IS_BUSY
    EQUIP_ERR_NONE = 58  # ERR_CANT_BE_DISENCHANTED
    EQUIP_ERR_NOT_IN_COMBAT = 59  # ERR_NOT_IN_COMBAT
    EQUIP_ERR_BAG_FULL6 = 60  # ERR_BAG_FULL
    EQUIP_ERR_CANT_EQUIP_RANK = 61  # ERR_CANT_EQUIP_RANK
