from enum import IntEnum


class PetReactState(IntEnum):
	REACT_PASSIVE = 0
	REACT_DEFENSIVE = 1
	REACT_AGGRESSIVE = 2


class PetCommandState(IntEnum):
	COMMAND_STAY = 0
	COMMAND_FOLLOW = 1
	COMMAND_ATTACK = 2
	COMMAND_DISMISS = 3


class PetActionBarIndex(IntEnum):
	INDEX_START = 0
	INDEX_SPELL_START = 3
	INDEX_REACT_START = 7
	INDEX_END = 10


class PetTameResult(IntEnum):
	TAME_SUCCESS = 0
	TAME_INVALID_CREATURE = 1
	TAME_TOO_MANY = 2
	TAME_CREATURE_ALREADY_OWNED = 3
	TAME_NOT_TAMABLE = 4
	TAME_ANOTHER_ACTIVE = 5
	TAME_UNITS_CANT_TAME = 6
	TAME_NO_PET_AVAILABLE = 7
	TAME_INTERNAL_ERROR = 8
	TAME_TOO_HIGH_LEVEL = 9


class PetSlot(IntEnum):
	PET_SLOT_PERMANENT = 0
	PET_SLOT_CHARM = 1
	PET_SLOT_TOTEM_START = 2
	PET_SLOT_END = 6
