from enum import IntEnum


class PetCommandState(IntEnum):
	COMMAND_STAY = 0
	COMMAND_FOLLOW = 1
	COMMAND_ATTACK = 2
	COMMAND_DISMISS = 3


class PetActionBarIndex(IntEnum):
	INDEX_START = 0
	INDEX_SPELL_START = 3
	INDEX_REACT_START = 7
	INDEX_END = 10


class PetTameResult(IntEnum):
	TAME_SUCCESS = 0
	TAME_INVALID_CREATURE = 1
	TAME_TOO_MANY = 2
	TAME_CREATURE_ALREADY_OWNED = 3
	TAME_NOT_TAMABLE = 4
	TAME_ANOTHER_ACTIVE = 5
	TAME_UNITS_CANT_TAME = 6
	TAME_NO_PET_AVAILABLE = 7
	TAME_INTERNAL_ERROR = 8
	TAME_TOO_HIGH_LEVEL = 9


class PetSlot(IntEnum):
	PET_SLOT_PERMANENT = 0
	PET_SLOT_CHARM = 1
	PET_SLOT_TOTEM_START = 2
	PET_SLOT_TOTEM_END = 6
	PET_SLOT_GUARDIAN_START = 7
	PET_SLOT_GUARDIAN_1 = 8
	PET_SLOT_GUARDIAN_2 = 9
	PET_SLOT_GUARDIAN_3 = 10
	PET_SLOT_GUARDIAN_4 = 11
	PET_SLOT_GUARDIAN_5 = 12
	PET_SLOT_GUARDIAN_6 = 13
	PET_SLOT_GUARDIAN_7 = 14
	PET_SLOT_GUARDIAN_8 = 15
	PET_SLOT_GUARDIAN_9 = 16
	PET_SLOT_GUARDIAN_10 = 17
	PET_SLOT_GUARDIAN_11 = 18
	PET_SLOT_GUARDIAN_12 = 19
	PET_SLOT_GUARDIAN_13 = 20
	PET_SLOT_GUARDIAN_14 = 21
	PET_SLOT_GUARDIAN_END = 22


class PetMoveState(IntEnum):
	AT_HOME = 0
	RETURNING = 1
	MOVE_RANGE = 2
	AT_RANGE = 3
