from enum import IntEnum


class ObjectFields(IntEnum):
    OBJECT_FIELD_GUID = 0x0
    OBJECT_FIELD_TYPE = 0x2
    OBJECT_FIELD_ENTRY = 0x3
    OBJECT_FIELD_SCALE_X = 0x4
    OBJECT_FIELD_PADDING = 0x5
    OBJECT_END = 0x6


class ItemFields(IntEnum):
    ITEM_FIELD_OWNER = ObjectFields.OBJECT_END + 0x0
    ITEM_FIELD_CONTAINED = ObjectFields.OBJECT_END + 0x2
    ITEM_FIELD_CREATOR = ObjectFields.OBJECT_END + 0x4
    ITEM_FIELD_STACK_COUNT = ObjectFields.OBJECT_END + 0x6
    ITEM_FIELD_DURATION = ObjectFields.OBJECT_END + 0x7
    ITEM_FIELD_SPELL_CHARGES = ObjectFields.OBJECT_END + 0x8
    ITEM_FIELD_FLAGS = ObjectFields.OBJECT_END + 0xD
    ITEM_FIELD_ENCHANTMENT = ObjectFields.OBJECT_END + 0xE
    ITEM_FIELD_PAD = ObjectFields.OBJECT_END + 0x1D
    ITEM_END = ObjectFields.OBJECT_END + 0x1E


class ContainerFields(IntEnum):
    CONTAINER_FIELD_NUM_SLOTS = ItemFields.ITEM_END + 0x0
    CONTAINER_ALIGN_PAD = ItemFields.ITEM_END + 0x1
    CONTAINER_FIELD_SLOT_1 = ItemFields.ITEM_END + 0x2
    CONTAINER_END = ItemFields.ITEM_END + 0x2A


class UnitFields(IntEnum):
    UNIT_FIELD_CHARM = ObjectFields.OBJECT_END + 0x0
    UNIT_FIELD_SUMMON = ObjectFields.OBJECT_END + 0x2
    UNIT_FIELD_CHARMEDBY = ObjectFields.OBJECT_END + 0x4
    UNIT_FIELD_SUMMONEDBY = ObjectFields.OBJECT_END + 0x6
    UNIT_FIELD_CREATEDBY = ObjectFields.OBJECT_END + 0x8
    UNIT_FIELD_TARGET = ObjectFields.OBJECT_END + 0xA
    UNIT_FIELD_COMBO_TARGET = ObjectFields.OBJECT_END + 0xC
    UNIT_FIELD_CHANNEL_OBJECT = ObjectFields.OBJECT_END + 0xE
    UNIT_FIELD_HEALTH = ObjectFields.OBJECT_END + 0x10
    UNIT_FIELD_POWER1 = ObjectFields.OBJECT_END + 0x11
    UNIT_FIELD_POWER2 = ObjectFields.OBJECT_END + 0x12
    UNIT_FIELD_POWER3 = ObjectFields.OBJECT_END + 0x13
    UNIT_FIELD_POWER4 = ObjectFields.OBJECT_END + 0x14
    UNIT_FIELD_MAXHEALTH = ObjectFields.OBJECT_END + 0x15
    UNIT_FIELD_MAXPOWER1 = ObjectFields.OBJECT_END + 0x16
    UNIT_FIELD_MAXPOWER2 = ObjectFields.OBJECT_END + 0x17
    UNIT_FIELD_MAXPOWER3 = ObjectFields.OBJECT_END + 0x18
    UNIT_FIELD_MAXPOWER4 = ObjectFields.OBJECT_END + 0x19
    UNIT_FIELD_LEVEL = ObjectFields.OBJECT_END + 0x1A
    UNIT_FIELD_FACTIONTEMPLATE = ObjectFields.OBJECT_END + 0x1B
    UNIT_FIELD_BYTES_0 = ObjectFields.OBJECT_END + 0x1C
    UNIT_FIELD_STAT0 = ObjectFields.OBJECT_END + 0x1D
    UNIT_FIELD_STAT1 = ObjectFields.OBJECT_END + 0x1E
    UNIT_FIELD_STAT2 = ObjectFields.OBJECT_END + 0x1F
    UNIT_FIELD_STAT3 = ObjectFields.OBJECT_END + 0x20
    UNIT_FIELD_STAT4 = ObjectFields.OBJECT_END + 0x21
    UNIT_FIELD_BASESTAT0 = ObjectFields.OBJECT_END + 0x22
    UNIT_FIELD_BASESTAT1 = ObjectFields.OBJECT_END + 0x23
    UNIT_FIELD_BASESTAT2 = ObjectFields.OBJECT_END + 0x24
    UNIT_FIELD_BASESTAT3 = ObjectFields.OBJECT_END + 0x25
    UNIT_FIELD_BASESTAT4 = ObjectFields.OBJECT_END + 0x26
    UNIT_VIRTUAL_ITEM_SLOT_DISPLAY = ObjectFields.OBJECT_END + 0x27
    UNIT_VIRTUAL_ITEM_INFO = ObjectFields.OBJECT_END + 0x2A
    UNIT_FIELD_FLAGS = ObjectFields.OBJECT_END + 0x30
    UNIT_FIELD_COINAGE = ObjectFields.OBJECT_END + 0x31
    UNIT_FIELD_AURA = ObjectFields.OBJECT_END + 0x32
    UNIT_FIELD_AURAFLAGS = ObjectFields.OBJECT_END + 0x6A
    UNIT_FIELD_AURASTATE = ObjectFields.OBJECT_END + 0x71
    UNIT_FIELD_MOD_DAMAGE_DONE = ObjectFields.OBJECT_END + 0x72
    UNIT_FIELD_MOD_DAMAGE_TAKEN = ObjectFields.OBJECT_END + 0x78
    UNIT_FIELD_MOD_CREATURE_DAMAGE_DONE = ObjectFields.OBJECT_END + 0x7E
    UNIT_FIELD_BASEATTACKTIME = ObjectFields.OBJECT_END + 0x86
    UNIT_FIELD_RESISTANCES = ObjectFields.OBJECT_END + 0x88
    UNIT_FIELD_BOUNDINGRADIUS = ObjectFields.OBJECT_END + 0x8E
    UNIT_FIELD_COMBATREACH = ObjectFields.OBJECT_END + 0x8F
    UNIT_FIELD_WEAPONREACH = ObjectFields.OBJECT_END + 0x90
    UNIT_FIELD_DISPLAYID = ObjectFields.OBJECT_END + 0x91
    UNIT_FIELD_MOUNTDISPLAYID = ObjectFields.OBJECT_END + 0x92
    UNIT_FIELD_DAMAGE = ObjectFields.OBJECT_END + 0x93
    UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE = ObjectFields.OBJECT_END + 0x94
    UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE = ObjectFields.OBJECT_END + 0x9A
    UNIT_FIELD_RESISTANCEITEMMODS = ObjectFields.OBJECT_END + 0xA0
    UNIT_FIELD_BYTES_1 = ObjectFields.OBJECT_END + 0xA6  # StandState NPCFlags ShapeshiftForm WeaponMode
    UNIT_FIELD_PETNUMBER = ObjectFields.OBJECT_END + 0xA7
    UNIT_FIELD_PET_NAME_TIMESTAMP = ObjectFields.OBJECT_END + 0xA8
    UNIT_FIELD_PETEXPERIENCE = ObjectFields.OBJECT_END + 0xA9
    UNIT_FIELD_PETNEXTLEVELEXP = ObjectFields.OBJECT_END + 0xAA
    UNIT_DYNAMIC_FLAGS = ObjectFields.OBJECT_END + 0xAB
    UNIT_EMOTE_STATE = ObjectFields.OBJECT_END + 0xAC
    UNIT_CHANNEL_SPELL = ObjectFields.OBJECT_END + 0xAD
    UNIT_MOD_CAST_SPEED = ObjectFields.OBJECT_END + 0xAE
    UNIT_CREATED_BY_SPELL = ObjectFields.OBJECT_END + 0xAF
    UNIT_FIELD_BYTES_2 = ObjectFields.OBJECT_END + 0xB0  # Combo Points pad pad pad
    UNIT_FIELD_PADDING = ObjectFields.OBJECT_END + 0xB1
    UNIT_END = ObjectFields.OBJECT_END + 0xB2


class PlayerFields(IntEnum):
    PLAYER_FIELD_INV_SLOT_1 = UnitFields.UNIT_END + 0x0
    PLAYER_FIELD_PACK_SLOT_1 = UnitFields.UNIT_END + 0x2E
    PLAYER_FIELD_BANK_SLOT_1 = UnitFields.UNIT_END + 0x4E
    PLAYER_FIELD_BANKBAG_SLOT_1 = UnitFields.UNIT_END + 0x7E
    PLAYER_SELECTION = UnitFields.UNIT_END + 0x8A  # Uint64 GUID
    PLAYER_FARSIGHT = UnitFields.UNIT_END + 0x8C  # Uint64 GUID ?
    PLAYER_DUEL_ARBITER = UnitFields.UNIT_END + 0x8E  # Uint64 GUID ?
    PLAYER_FIELD_NUM_INV_SLOTS = UnitFields.UNIT_END + 0x90
    PLAYER_GUILDID = UnitFields.UNIT_END + 0x91
    PLAYER_GUILDRANK = UnitFields.UNIT_END + 0x92
    PLAYER_BYTES = UnitFields.UNIT_END + 0x93
    PLAYER_XP = UnitFields.UNIT_END + 0x94
    PLAYER_NEXT_LEVEL_XP = UnitFields.UNIT_END + 0x95
    PLAYER_SKILL_INFO_1_1 = UnitFields.UNIT_END + 0x96
    PLAYER_BYTES_2 = UnitFields.UNIT_END + 0x156
    PLAYER_QUEST_LOG_1_1 = UnitFields.UNIT_END + 0x157
    PLAYER_CHARACTER_POINTS1 = UnitFields.UNIT_END + 0x1B7
    PLAYER_CHARACTER_POINTS2 = UnitFields.UNIT_END + 0x1B8
    PLAYER_TRACK_CREATURES = UnitFields.UNIT_END + 0x1B9
    PLAYER_TRACK_RESOURCES = UnitFields.UNIT_END + 0x1BA
    PLAYER_CHAT_FILTERS = UnitFields.UNIT_END + 0x1BB
    PLAYER_DUEL_TEAM = UnitFields.UNIT_END + 0x1BC
    PLAYER_BLOCK_PERCENTAGE = UnitFields.UNIT_END + 0x1BD
    PLAYER_DODGE_PERCENTAGE = UnitFields.UNIT_END + 0x1BE
    PLAYER_PARRY_PERCENTAGE = UnitFields.UNIT_END + 0x1BF
    PLAYER_BASE_MANA = UnitFields.UNIT_END + 0x1C0
    PLAYER_GUILD_TIMESTAMP = UnitFields.UNIT_END + 0x1C1
    PLAYER_END = UnitFields.UNIT_END + 0x1C2


class GameObjectFields(IntEnum):
    GAMEOBJECT_DISPLAYID = ObjectFields.OBJECT_END + 0x0
    GAMEOBJECT_FLAGS = ObjectFields.OBJECT_END + 0x1
    GAMEOBJECT_ROTATION = ObjectFields.OBJECT_END + 0x2
    GAMEOBJECT_STATE = ObjectFields.OBJECT_END + 0x6
    GAMEOBJECT_TIMESTAMP = ObjectFields.OBJECT_END + 0x7
    GAMEOBJECT_POS_X = ObjectFields.OBJECT_END + 0x8
    GAMEOBJECT_POS_Y = ObjectFields.OBJECT_END + 0x9
    GAMEOBJECT_POS_Z = ObjectFields.OBJECT_END + 0xA
    GAMEOBJECT_FACING = ObjectFields.OBJECT_END + 0xB
    GAMEOBJECT_DYN_FLAGS = ObjectFields.OBJECT_END + 0xC
    GAMEOBJECT_FACTION = ObjectFields.OBJECT_END + 0xD
    GAMEOBJECT_END = ObjectFields.OBJECT_END + 0xE


class DynamicObjectFields(IntEnum):
    DYNAMICOBJECT_CASTER = ObjectFields.OBJECT_END + 0x0
    DYNAMICOBJECT_BYTES = ObjectFields.OBJECT_END + 0x2
    DYNAMICOBJECT_SPELLID = ObjectFields.OBJECT_END + 0x3
    DYNAMICOBJECT_RADIUS = ObjectFields.OBJECT_END + 0x4
    DYNAMICOBJECT_POS_X = ObjectFields.OBJECT_END + 0x5
    DYNAMICOBJECT_POS_Y = ObjectFields.OBJECT_END + 0x6
    DYNAMICOBJECT_POS_Z = ObjectFields.OBJECT_END + 0x7
    DYNAMICOBJECT_FACING = ObjectFields.OBJECT_END + 0x8
    DYNAMICOBJECT_PAD = ObjectFields.OBJECT_END + 0x9
    DYNAMICOBJECT_END = ObjectFields.OBJECT_END + 0xA
