class Constants:
    MAPS_VERSION = 'ACMAP_1.70'
    TILE_BLOCK_SIZE = 64
    TILE_SIZE = 16
    CELL_SIZE = 8
    GRID_SIZE = TILE_SIZE * CELL_SIZE
    TILE_SIZE_YARDS = 533.3333333
    CHUNK_SIZE = TILE_SIZE_YARDS / TILE_SIZE
    UNIT_SIZE = CHUNK_SIZE / 8.0
