class Constants:
    MAPS_VERSION = 'ACMAP_1.92'
    HEIGHTMAP_MODE_UNIFORM = 0
    HEIGHTMAP_MODE_V8V9 = 1
    LIQUID_FLAG_IS_WMO = 0x1
    TILE_BLOCK_SIZE = 64
    TILE_SIZE = 16
    CELL_SIZE = 8
    GRID_SIZE = TILE_SIZE * CELL_SIZE
    TILE_SIZE_YARDS = 533.3333333
    CHUNK_SIZE = TILE_SIZE_YARDS / TILE_SIZE
    UNIT_SIZE = CHUNK_SIZE / 8.0
