name: BuildTestDeploy

on:
  push:
    branches: [ Nam ]
  pull_request:
    branches: [ Nam ]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Checkout submodules
      run: git submodule update --init --recursive      

    - name: Configure CMake
      working-directory: ${{github.workspace}}/contrib/namigator/
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/contrib/namigator/
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Install
      working-directory: ${{github.workspace}}/contrib/namigator/
      run: cmake --install build --prefix ${{github.workspace}}/contrib/namigator/install
    
    - name: Rename libs
      working-directory: ${{github.workspace}}/
      run: |
        cd ${{github.workspace}}/contrib/namigator/install/namigator/
        find . -iname "*mapbuild*" -execdir mv {} mapbuild.so \;
        find . -iname "*pathfind*" -execdir mv {} pathfind.so \;
        
    - name: Test
      working-directory: ${{github.workspace}}/contrib/namigator/install/
      run: test/smoke_tests.py
      
    - name: Copy namigator libs
      working-directory: ${{github.workspace}}/
      run: |
        mv ${{github.workspace}}/contrib/namigator/install/namigator/* ${{github.workspace}}/namigator/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: namigator_linux
        path: ${{github.workspace}}
        retention-days: 5

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodules
      run: git submodule update --init --recursive
    
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Configure CMake
      working-directory: ${{github.workspace}}/contrib/namigator/
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/contrib/namigator/
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Install
      working-directory: ${{github.workspace}}/contrib/namigator/
      run: cmake --install build --prefix ${{github.workspace}}/contrib/namigator/install
      
    - name: Test
      working-directory: ${{github.workspace}}/contrib/namigator/install/
      run: python test/smoke_tests.py
      
    - name: Create dir
      working-directory: ${{github.workspace}}/
      run: |
        mv ${{github.workspace}}/contrib/namigator/install/namigator/* ${{github.workspace}}/namigator/
        cd ${{github.workspace}}/namigator/
        find . -iname "*mapbuild*" -execdir mv {} mapbuild.pyd \;
        find . -iname "*pathfind*" -execdir mv {} pathfind.pyd \;
        rm -rf ${{github.workspace}}/contrib
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: namigator_windows
        path: ${{github.workspace}}/contrib/namigator/install/
        retention-days: 5
